In [1]:
# import dependencies
import pandas as pd
import numpy as np

In [2]:
# assign federal dataset path to variable
csv_path = "geojson/state_code.csv"

# load csv
state_codes = pd.read_csv(csv_path, encoding="utf8")
state_codes.head(1)

  State/District Postal Code
0        Alabama          AL

In [3]:
# assign federal dataset path to variable
csv_path = "geojson/0_raw/state_boundaries.csv"

# load csv
boundaries = pd.read_csv(csv_path, encoding="utf8", low_memory=False)
boundaries.head(1)

     State  SouthBoundary  NorthBoundary  WestBoundary  EastBoundary
0  Alabama      30.216667           35.0        -84.85    -88.466667

In [4]:
state_boundaries = boundaries.merge(state_codes, left_on=["State"], right_on=["State/District"])
state_boundaries = state_boundaries[["State","SouthBoundary","NorthBoundary","WestBoundary","EastBoundary","Postal Code"]]
state_boundaries = state_boundaries.rename(columns={"Postal Code":"State_Abbreviation"})
state_boundaries

,State,SouthBoundary,NorthBoundary,WestBoundary,EastBoundary,State_Abbreviation
0,Alabama,30.216667,35.000000,-84.850000,-88.466667,AL
1,Alaska,54.666667,71.833333,-130.000000,173.000000,AK
2,Arizona,31.333333,37.000000,-109.050000,-114.833333,AZ
3,Arkansas,33.000000,36.500000,-89.683333,-94.700000,AR
4,California,32.500000,42.000000,-114.133333,-124.400000,CA
5,Colorado,37.000000,41.000000,-102.000000,-109.000000,CO
6,Connecticut,40.966667,42.050000,-71.783333,-73.733333,CT
7,Delaware,38.450000,39.833333,-75.033333,-75.783333,DE
8,Florida,24.500000,31.000000,-79.800000,-87.633333,FL
9,Georgia,30.000000,35.000000,-81.000000,-85.000000,GA
10,Hawaii,16.916667,23.000000,-154.666667,-162.000000,HI
11,Idaho,42.000000,49.000000,-111.000000,-117.000000,ID
12,Illinois,36.966667,42.500000,-87.500000,-91.500000,IL
13,Indiana,37.783333,41.766667,-84.816667,-88.066667,IN
14,Iowa,40.600000,43.500000,-89.083333,-96.516667,IA
15,Kansas,37.000000,40.000000,-94.633333,-102.026111,KS
16,Kentucky,36.500000,39.150000,-81.966667,-89.566667,KY
17,Louisiana,29.000000,33.000000,-89.000000,-94.000000,LA
18,Maine,43.066667,47.466667,-66.950000,-71.116667,ME
19,Maryland,37.883333,39.716667,-75.066667,-79.550000,MD
20,Massachusetts,41.166667,42.883333,-69.950000,-73.500000,MA
21,Michigan,41.683333,48.250000,-82.433333,-90.516667,MI
22,Minnesota,43.566667,49.383333,-89.566667,-97.200000,MN
23,Mississippi,30.216667,35.000000,-88.116667,-91.683333,MS
24,Missouri,36.000000,40.583333,-89.100000,-95.700000,MO
25,Montana,44.433333,49.000000,-104.033333,-116.033333,MT
26,Nebraska,40.000000,43.000000,-95.416667,-104.000000,NE
27,Nevada,35.000000,42.000000,-114.000000,-120.000000,NV
28,New Hampshire,42.666667,45.300000,-70.616667,-72.000000,NH
29,New Jersey,38.916667,41.356389,-73.894167,-75.583333,NJ
30,New Mexico,31.333333,37.000000,-103.000000,-109.000000,NM
31,New York,40.494444,45.011667,-71.790278,-79.765000,NY
32,North Carolina,34.000000,36.350000,-75.500000,-84.250000,NC
33,North Dakota,45.916667,49.000000,-97.000000,-104.000000,ND
34,Ohio,38.450000,41.966667,-80.533333,-84.816667,OH
35,Oklahoma,33.583333,37.000000,-94.483333,-103.000000,OK
36,Oregon,42.000000,46.250000,-116.750000,-124.500000,OR
37,Pennsylvania,39.716667,42.000000,-74.716667,-80.516667,PA
38,Rhode Island,41.300000,42.016667,-71.133333,-71.883333,RI
39,South Carolina,32.075000,35.200000,-78.008333,-83.333333,SC
40,South Dakota,42.491667,45.933333,-97.475833,-104.050000,SD
41,Tennessee,35.000000,36.683333,-81.616667,-90.466667,TN
42,Texas,25.833333,36.500000,-93.516667,-106.633333,TX
43,Utah,37.000000,42.000000,-109.000000,-114.000000,UT
44,Vermont,42.733333,45.011944,-71.466667,-73.433333,VT
45,Virginia,36.516667,39.616667,-75.216667,-83.616667,VA
46,Washington,45.533333,49.000000,-116.950000,-124.800000,WA
47,West Virginia,37.166667,40.666667,-77.666667,-82.666667,WV
48,Wisconsin,42.500000,47.050000,-86.816667,-92.900000,WI
49,Wyoming,41.000000,45.000000,-104.050000,-111.050000,WY

In [5]:
# export dataframe as a csv
state_boundaries.to_csv("geojson/state_boundaries.csv", index=False)