In [1]:
# !pip install sqlalchemy
# !pip install pymysql

In [2]:
# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Config variables
from config import dbuser, dbpwd, dbhost, dbport, dbname

# Import Pandas
import pandas as pd

In [3]:
# Cloud MySQL Database Connection on AWS
engine = create_engine(f"mysql://{dbuser}:{dbpwd}@{dbhost}:{dbport}/{dbname}")

In [4]:
# Create a remote database engine connection
conn = engine.connect()

In [5]:
csv_data = pd.read_csv('Tunnel_Data_Cleaned.csv')
csv_data.head()

,Unnamed: 0,Tunnel_Number,Tunnel_Name,State_Code,Route_Type,Latitude,Longitude,Year_Built,Year_Rehabilitated,Lanes,...,Toll,NHS,STRAHNET,Class,Length,Under_Nav_Water,Number_Bores,Tunnel_Shape,Ground_Conditions,Condition
0,0,53C1210,Hope Street Tunnel,California,City Street,34.048339,-118.257256,1972,0,4,...,0,0,1,Minor Arterial,75,0,1,Oval,Soil,2
1,1,1113,12th St SW Tunnel at Southwest Fwy,District of Columbia,City Street,38.882778,-77.028056,1959,0,4,...,0,1,0,Minor Arterial,295,0,1,Oval,Soil,2
2,2,IN2MARION000001,South Capitol Avenue under CSX RR and Other Items,Indiana,City Street,39.762910,86.161866,1888,1984,4,...,0,0,0,Minor Arterial,353,0,1,Oval,Soil,13
3,3,IN2MARION000002,Illinois Street under CSX RR and Other Items,Indiana,City Street,39.762042,86.160099,1888,1984,4,...,0,0,0,Minor Arterial,310,0,1,Oval,Soil,4
4,4,IN2MARION000003,Meridian Street under CSX RR and Other Items,Indiana,City Street,39.762023,86.158331,1888,1984,4,...,0,0,0,Minor Arterial,276,0,1,Oval,Soil,15

In [6]:
csv_data.to_sql(name='tunnels', if_exists='append', con=conn, chunksize=500, index=False)