In [1]:
# import dependencies
import pandas as pd
import numpy as np

In [2]:
# assign federal dataset path to variable
csv_path = "geojson/state_code.csv"

# load csv
state_codes = pd.read_csv(csv_path, encoding="utf8")
state_codes.head(1)

  State/District Postal Code
0        Alabama          AL

### spending_state-local_2017dollars

In [3]:
# assign federal dataset path to variable
csv_path = "expenditures/by_state/1_clean/spending_state-local_2017dollars.csv"

# load csv
state_totals = pd.read_csv(csv_path, encoding="utf8", low_memory=False)
state_totals.head(1)

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay
0,United States,1977,1366644562,1312783911,93266505,42485760,50780746,90317388,40734171,49583217,2949117,1751589,1197528

In [4]:
state_abbr = []

# for i in range(0,1): # use for testing
for i in range(0,len(state_totals)):
    
#     print(f"Processing index {i}...")
    
    df_name = state_totals['State'][i].lower()
    # print(df_name)
    
    if df_name == "united states":
        state_abbr.append("US")
        
    elif df_name == "dc":
            state_abbr.append("DC")
    
    else:
        for j in range(0,len(state_codes)):

            name = state_codes["State/District"][j].lower()
            code = state_codes["Postal Code"][j]

            if  df_name == name:
                state_abbr.append(code)

state_totals['State_Abbreviation'] = state_abbr
state_totals.head()

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,United States,1977,1366644562,1312783911,93266505,42485760,50780746,90317388,40734171,49583217,2949117,1751589,1197528,US
1,United States,1978,1397060275,1303751373,92516739,44026936,48489804,89750496,42298080,47452416,2766243,1728855,1037388,US
2,United States,1979,1367037303,1289301287,96022532,43465121,52557412,93130083,41812327,51317756,2892450,1652794,1239656,US
3,United States,1980,1343211785,1291262980,99092991,42175481,56917510,95916322,40573137,55343185,3176669,1602344,1574325,US
4,United States,1981,1366436974,1313366901,93310461,41174187,52136274,90318331,39588900,50729431,2992130,1585287,1406843,US

In [5]:
state_totals = state_totals.reset_index()
state_totals = state_totals.rename(columns={"index":"ID"})
state_totals["ID"] = state_totals["ID"] + 1
state_totals.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,1,United States,1977,1366644562,1312783911,93266505,42485760,50780746,90317388,40734171,49583217,2949117,1751589,1197528,US
1,2,United States,1978,1397060275,1303751373,92516739,44026936,48489804,89750496,42298080,47452416,2766243,1728855,1037388,US
2,3,United States,1979,1367037303,1289301287,96022532,43465121,52557412,93130083,41812327,51317756,2892450,1652794,1239656,US
3,4,United States,1980,1343211785,1291262980,99092991,42175481,56917510,95916322,40573137,55343185,3176669,1602344,1574325,US
4,5,United States,1981,1366436974,1313366901,93310461,41174187,52136274,90318331,39588900,50729431,2992130,1585287,1406843,US

In [6]:
# export dataframe as csv
state_totals.to_csv("expenditures/by_state/spending_state-local_2017dollars.csv")

### spending_state-local_fraction-exp

In [7]:
# assign federal dataset path to variable
csv_path = "expenditures/by_state/1_clean/spending_state-local_fraction-exp.csv"

# load csv
state_fraction = pd.read_csv(csv_path, encoding="utf8", low_memory=False)
state_fraction.head(1)

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay
0,United States,1977,1.041,1,0.071,0.0324,0.0387,0.0688,0.031,0.0378,0.0022,0.0013,0.0009

In [8]:
state_abbr = []

# for i in range(0,1): # use for testing
for i in range(0,len(state_fraction)):
    
#     print(f"Processing index {i}...")
    
    df_name = state_fraction['State'][i].lower()
    # print(df_name)
    
    if df_name == "united states":
        state_abbr.append("US")
        
    elif df_name == "dc":
            state_abbr.append("DC")
    
    else:
        for j in range(0,len(state_codes)):

            name = state_codes["State/District"][j].lower()
            code = state_codes["Postal Code"][j]

            if  df_name == name:
                state_abbr.append(code)

state_fraction['State_Abbreviation'] = state_abbr
state_fraction.head()

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,United States,1977,1.0410,1,0.0710,0.0324,0.0387,0.0688,0.0310,0.0378,0.0022,0.0013,0.0009,US
1,United States,1978,1.0716,1,0.0710,0.0338,0.0372,0.0688,0.0324,0.0364,0.0021,0.0013,0.0008,US
2,United States,1979,1.0603,1,0.0745,0.0337,0.0408,0.0722,0.0324,0.0398,0.0022,0.0013,0.0010,US
3,United States,1980,1.0402,1,0.0767,0.0327,0.0441,0.0743,0.0314,0.0429,0.0025,0.0012,0.0012,US
4,United States,1981,1.0404,1,0.0710,0.0314,0.0397,0.0688,0.0301,0.0386,0.0023,0.0012,0.0011,US

In [9]:
state_fraction = state_fraction.reset_index()
state_fraction = state_fraction.rename(columns={"index":"ID"})
state_fraction["ID"] = state_fraction["ID"] + 1
state_fraction.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,1,United States,1977,1.0410,1,0.0710,0.0324,0.0387,0.0688,0.0310,0.0378,0.0022,0.0013,0.0009,US
1,2,United States,1978,1.0716,1,0.0710,0.0338,0.0372,0.0688,0.0324,0.0364,0.0021,0.0013,0.0008,US
2,3,United States,1979,1.0603,1,0.0745,0.0337,0.0408,0.0722,0.0324,0.0398,0.0022,0.0013,0.0010,US
3,4,United States,1980,1.0402,1,0.0767,0.0327,0.0441,0.0743,0.0314,0.0429,0.0025,0.0012,0.0012,US
4,5,United States,1981,1.0404,1,0.0710,0.0314,0.0397,0.0688,0.0301,0.0386,0.0023,0.0012,0.0011,US

In [10]:
# export dataframe as csv
state_fraction.to_csv("expenditures/by_state/spending_state-local_fraction-exp.csv")

### spending_state-local_per-capita

In [11]:
# assign federal dataset path to variable
csv_path = "expenditures/by_state/1_clean/spending_state-local_per-capita.csv"

# load csv
state_capita = pd.read_csv(csv_path, encoding="utf8", low_memory=False)
state_capita.head(1)

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay
0,United States,1977,6219,5974,424,193,231,411,185,226,13,8,5

In [12]:
state_abbr = []

# for i in range(0,1): # use for testing
for i in range(0,len(state_capita)):
    
#     print(f"Processing index {i}...")
    
    df_name = state_capita['State'][i].lower()
    # print(df_name)
    
    if df_name == "united states":
        state_abbr.append("US")
        
    elif df_name == "dc":
            state_abbr.append("DC")
    
    else:
        for j in range(0,len(state_codes)):

            name = state_codes["State/District"][j].lower()
            code = state_codes["Postal Code"][j]

            if  df_name == name:
                state_abbr.append(code)

state_capita['State_Abbreviation'] = state_abbr
state_capita.head()

,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,United States,1977,6219,5974,424,193,231,411,185,226,13,8,5,US
1,United States,1978,6290,5870,417,198,218,404,190,214,12,8,5,US
2,United States,1979,6087,5741,428,194,234,415,186,229,13,7,6,US
3,United States,1980,5911,5683,436,186,250,422,179,244,14,7,7,US
4,United States,1981,5955,5724,407,179,227,394,173,221,13,7,6,US

In [13]:
state_capita = state_capita.reset_index()
state_capita = state_capita.rename(columns={"index":"ID"})
state_capita["ID"] = state_capita["ID"] + 1
state_capita.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,2,United States,1977,1.0410,1,0.0710,0.0324,0.0387,0.0688,0.0310,0.0378,0.0022,0.0013,0.0009,US
1,3,United States,1978,1.0716,1,0.0710,0.0338,0.0372,0.0688,0.0324,0.0364,0.0021,0.0013,0.0008,US
2,4,United States,1979,1.0603,1,0.0745,0.0337,0.0408,0.0722,0.0324,0.0398,0.0022,0.0013,0.0010,US
3,5,United States,1980,1.0402,1,0.0767,0.0327,0.0441,0.0743,0.0314,0.0429,0.0025,0.0012,0.0012,US
4,6,United States,1981,1.0404,1,0.0710,0.0314,0.0397,0.0688,0.0301,0.0386,0.0023,0.0012,0.0011,US

In [14]:
# export dataframe as csv
state_capita.to_csv("expenditures/by_state/spending_state-local_per-capita.csv")