In [1]:
# import dependencies
import pandas as pd

In [2]:
# assign dataset path to variable
csv_path = "datasets/federal_v_state/federal_total_CL-OM_2017dollars.csv"

# load csv
fed_breakdown = pd.read_csv(csv_path)
fed_breakdown.head()

# transpose table
fed_breakdown = fed_breakdown.rename(columns={"Unnamed: 0":"Spending"})
fed_breakdown = fed_breakdown.set_index("Spending")
del fed_breakdown.index.name
fed_breakdown = fed_breakdown.transpose()
fed_breakdown.head()

,All (Total),All (Capital),All (O&M),Highways (Total),Highways (Capital),Highways (O&M),Mass Transit (Total),Mass Transit (Capital),Mass Transit (O&M),Rail (Total),...,Aviation (O&M),Water Transportation (Total),Water Transportation (Capital),Water Transportation (O&M),Water Resources (Total),Water Resources (Capital),Water Resources (O&M),Water Utilities (Total),Water Utilities (Capital),Water Utilities (O&M)
1956,"21,635","16,211","5,424","10,206","9,695",511,0,0,0,87,...,"1,663",963,322,641,"8,366","5,844","2,522",0,0,0
1957,"25,008","18,886","6,122","12,372","11,884",488,0,0,0,105,...,"1,843",826,289,537,"9,294","6,146","3,149",21,21,0
1958,"33,013","28,150","4,862","19,231","19,037",194,0,0,0,139,...,"2,185",940,354,586,"9,166","7,408","1,758",190,190,0
1959,"52,007","44,194","7,813","33,416","33,094",321,0,0,0,115,...,"3,198",934,319,615,"11,945","8,382","3,563",381,381,0
1960,"58,568","50,215","8,353","38,899","38,413",486,0,0,0,95,...,"3,810","1,090",453,637,"12,110","8,785","3,325",431,431,0