In [1]:
# !pip install sqlalchemy
# !pip install pymysql

In [2]:
# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Config variables
import sys
sys.path.append('..')
from config import remote_gwsis_dbuser, remote_gwsis_dbpwd, remote_db_host, remote_db_port, remote_gwsis_dbname

# Import Pandas
import pandas as pd

In [3]:
# Cloud MySQL Database Connection on AWS
engine = create_engine(f"mysql://{remote_gwsis_dbuser}:{remote_gwsis_dbpwd}@{remote_db_host}:{remote_db_port}/{remote_gwsis_dbname}")

In [4]:
# Create a remote database engine connection
conn = engine.connect()

### spending_state-local_2017dollars

In [5]:
csv_data = pd.read_csv('expenditures/by_state/spending_state-local_2017dollars.csv')
csv_data = csv_data.set_index("Unnamed: 0")
del csv_data.index.name
csv_data.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,1,United States,1977,1366644562,1312783911,93266505,42485760,50780746,90317388,40734171,49583217,2949117,1751589,1197528,US
1,2,United States,1978,1397060275,1303751373,92516739,44026936,48489804,89750496,42298080,47452416,2766243,1728855,1037388,US
2,3,United States,1979,1367037303,1289301287,96022532,43465121,52557412,93130083,41812327,51317756,2892450,1652794,1239656,US
3,4,United States,1980,1343211785,1291262980,99092991,42175481,56917510,95916322,40573137,55343185,3176669,1602344,1574325,US
4,5,United States,1981,1366436974,1313366901,93310461,41174187,52136274,90318331,39588900,50729431,2992130,1585287,1406843,US

In [6]:
csv_data.to_sql(name='spending_bystate_2017dollars', if_exists='replace', con=conn, chunksize=500, index=False)

### spending_state-local_fraction-exp

In [7]:
csv_data = pd.read_csv('expenditures/by_state/spending_state-local_fraction-exp.csv')
csv_data = csv_data.set_index("Unnamed: 0")
del csv_data.index.name
csv_data.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,1,United States,1977,1.0410,1,0.0710,0.0324,0.0387,0.0688,0.0310,0.0378,0.0022,0.0013,0.0009,US
1,2,United States,1978,1.0716,1,0.0710,0.0338,0.0372,0.0688,0.0324,0.0364,0.0021,0.0013,0.0008,US
2,3,United States,1979,1.0603,1,0.0745,0.0337,0.0408,0.0722,0.0324,0.0398,0.0022,0.0013,0.0010,US
3,4,United States,1980,1.0402,1,0.0767,0.0327,0.0441,0.0743,0.0314,0.0429,0.0025,0.0012,0.0012,US
4,5,United States,1981,1.0404,1,0.0710,0.0314,0.0397,0.0688,0.0301,0.0386,0.0023,0.0012,0.0011,US

In [8]:
csv_data.to_sql(name='spending_bystate_fraction_exp', if_exists='replace', con=conn, chunksize=500, index=False)

### spending_state-local_per-capita

In [9]:
csv_data = pd.read_csv('expenditures/by_state/spending_state-local_per-capita.csv')
csv_data = csv_data.set_index("Unnamed: 0")
del csv_data.index.name
csv_data.head()

,ID,State,Year,(R01) Total Revenue,(E001) Total Expenditure,(E065) Total Highways-Dir Exp,(E066) Total Highways-Cur Op,(E067) Total Highways-Cap Out,(E068) Regular Hwy-Direct Exp,(E069) Regular Hwy-Cur Oper (E44),(E070) Regular Hwy-Cap Outlay,(E071) Toll Hwy-Total Expend,(E072) Toll Hwy-Current Oper (E45),(E073) Toll Hwy-Cap Outlay,State_Abbreviation
0,2,United States,1977,1.0410,1,0.0710,0.0324,0.0387,0.0688,0.0310,0.0378,0.0022,0.0013,0.0009,US
1,3,United States,1978,1.0716,1,0.0710,0.0338,0.0372,0.0688,0.0324,0.0364,0.0021,0.0013,0.0008,US
2,4,United States,1979,1.0603,1,0.0745,0.0337,0.0408,0.0722,0.0324,0.0398,0.0022,0.0013,0.0010,US
3,5,United States,1980,1.0402,1,0.0767,0.0327,0.0441,0.0743,0.0314,0.0429,0.0025,0.0012,0.0012,US
4,6,United States,1981,1.0404,1,0.0710,0.0314,0.0397,0.0688,0.0301,0.0386,0.0023,0.0012,0.0011,US

In [10]:
csv_data.to_sql(name='spending_bystate_percapita_2017dollars', if_exists='replace', con=conn, chunksize=500, index=False)